### ISSUE TITLE
Additional functionallity possible?

### ISSUE THREAD

**Issue by Samfox2** [Danimal4326/homebridge-hyperion#1]
Hi, thanks for the plugin, it´s really great!
I wonder if it is possible to add an option to switch between "lightbulb modus" (that is actually implemented and allows to change colors and turning on/off the attached led stripes) to ambilight (tv-capture) modus and back?

**Comment by Danimal4326** [comment]
Hmm, the only thing I can think of is creating another 'switch' that would show up in homekit, that you could turn on/off Ambilight mode.  On=ambilight mode off=lights off?

**Comment by Samfox2** [comment]
If thats possible it would be great.

**Comment by Samfox2** [comment]
Ok, I tested a bit. It's possible to add an additional switch service. Do you know whats the hyperion comand for setting the output to the grabber?

**Comment by Danimal4326** [comment]
I believe it's the clear command.  I used the Hyperion source to figure out
the commands.

On Sunday, November 15, 2015, Samfox2 notifications@github.com wrote:

> Ok, I tested a bit. It's possible to add an additional switch service. Do
> you know whats the hyperion comand for setting the output to the grabber?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Danimal4326/homebridge-hyperion/issues/1#issuecomment-156865361
> .

## 

Dan Chlopek
danimal4326@gmail.com dan.chlopek@gmail.com

**Comment by Danimal4326** [comment]
I've got some code ready to add an additional switch.  The only way I figured it out was to switch to a 'platform' type plugin.  Did you figure out another way?

**Comment by Samfox2** [comment]
I added an additional switch with a new service like below which points to a new function called "setAmbilightState" in which the correct command (I couldn`t get it to work) has to be added. This works with the existing "accessory".

```
 HyperionAccessory.prototype.getServices = function() {
 var switchservice = new Service.Switch("Ambilight");
 switchservice.getCharacteristic(Characteristic.On)
                .on('set', this.setAmbilightState.bind(this));

return [this.service,switchservice];
}
```

**Comment by Samfox2** [comment]
Great, thanks!
