### ISSUE TITLE
Can you add hyperion effects?

### ISSUE THREAD

**Issue by BTopbas** [Danimal4326/homebridge-hyperion#4]
Hyperion have 10+ effects and usage with ssh hyperion-remote --effect "Rainbow swirl fast" --duration 3000 anyone add this to here?

**Comment by Danimal4326** [comment]
I think that is out of scope of this implementation.   The main idea behind this plugin is to control the hyperion server as a light. 

You could possibly do this if you define a on/off switch for each effect.
