### ISSUE TITLE
color.rgbArray is not a function

### ISSUE THREAD

**Issue by JanJK2011** [Danimal4326/homebridge-hyperion#9]
Hi,

after Installation and configuration homebridge crashes when I try to turn on or off my Ambilight.
On the console I'm getting the following error:

> 
> TypeError: color.rgbArray is not a function
>     at HyperionAccessory.sendHyperionCommand (/usr/local/lib/node_modules/homebridge-hyperion/index.js:55:30)
>     at HyperionAccessory.setSaturation (/usr/local/lib/node_modules/homebridge-hyperion/index.js:149:10)
>     at emitMany (events.js:108:13)
>     at emit (events.js:182:7)
>     at Characteristic.setValue (/usr/local/lib/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
>     at Bridge.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:727:22)
>     at Array.forEach (native)
>     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:672:8)
>     at emitMany (events.js:108:13)
>     at HAPServer.emit (events.js:182:7)
>     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:966:10)
>     at HAPServer.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:203:39)
>     at emitNone (events.js:67:13)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:921:12)
>     at nextTickCallbackWith2Args (node.js:442:9)
> 
> 
> 

Do you know what I'm doing wrong here?!

**Comment by werthdavid** [comment]
Not your fault, the 'color' dependency has breaking changes. Maybe I'll find time to upload a fix the next days..

**Comment by fugazzy** [comment]
I have the same problem, any news on this? How to solve this?

**Comment by werthdavid** [comment]
I created a pull-request (hotfix) but no reaction from Danimal yet.. Maybe I'll publish a working fork to npm later today, I'll keep you posted

**Comment by Danimal4326** [comment]
Just merged. Sorry for the delay.
